// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrunjopwxqafhinsnmou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydW5qb3B3eHFhZmhpbnNubW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzkwOTQsImV4cCI6MjA3NDIxNTA5NH0.mRG0XCFz5pEXVYI-LL4iR0A6z6D5bbmtzwJ6-c77UrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});